trigger: none

jobs:
- job: buildandtest
  pool:
    name: 'Self-hosted'
  
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages - dotnet restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
    
  - task: DotNetCoreCLI@2
    displayName: Build the project - dotnet build
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: dependency-check-build-task@6
    displayName: Dependency Checker - Security
    continueOnError: true
    inputs:
      projectName: 'Dependency.Check'
      scanPath: '**/*.csproj'
      format: 'HTML, JSON, JUNIT'
      failOnCVSS: '8'
      nvdApiKey: $(nvdapi)

  - task: PublishTestResults@2
    displayName: "Publish Dependency Checks Tests Results"
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Agent.BuildDirectory)/TestResults/dependency-check/*junit.xml'
      mergeTestResults: true
